### ISSUE TITLE
CODE NO BE THE WORKING

### ISSUE THREAD

**Issue by tazule** [bsaund/TeamError404#3]
MMMMMMMMMMMMMMMEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by bsaund** [comment]
Someone fix this fast! The robot is on fire!!!!! :fire:

**Comment by tazule** [comment]
apparently setting motor to EXPLODE  was a bad idea

**Comment by maddylee** [comment]
ok ill call jimmy johns

**Comment by maddylee** [comment]
-maddy

**Comment by emilyhinds** [comment]
all hail the mighty jimmy

**Comment by tazule** [comment]
:8ball:

**Comment by maddylee** [comment]
:)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by emilyhinds** [comment]
### IMPORTANT

##IMPORTANTER
#IMPORTANTIST

**Comment by emilyhinds** [comment]
- [x] do
- [x] to

**Comment by tazule** [comment]
//GET COMMENTED

**Comment by emilyhinds** [comment]
@tazule howdy bruh

**Comment by tazule** [comment]
howdy

**Comment by emilyhinds** [comment]
@jacobseattle do u even read

**Comment by tazule** [comment]
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111

**Comment by maddylee** [comment]
i found the zero

**Comment by jacobseattle** [comment]
Do I read code?

**Comment by emilyhinds** [comment]
@bsaund name your first child whiskers 
-the whole team

**Comment by bsaund** [comment]
@theWholeTeam No promises
